### ISSUE TITLE
validation: ARC and CIE batches with Service Class Code Mixed (200) fails

### ISSUE THREAD

**Issue by vxio** [moov-io/ach#833] opened 2021-01-14 20:51 UTC
Version: `v1.6.0`

**What were you trying to do?**
Validate ARC and CIE batches with Service Class Code (SCC) Mixed Debits and Credits (`200`). 

**What did you expect to see?**
The validation to succeed since the NACHA spec does not forbid the use of SSC 200 on ARC (debits only) and CIE (credits only) batches.

**What did you see?**
The validation fails since the library prevents the use of SSC 200 on ARC or CIE batches.

--------------
Reported by @Deiz in the ACH Slack channel.

**Possible solution**:
On the `ValidateOpts` struct, add a boolean flag, like `IgnoreSCCValidation` to ignore the debits/credits only restriction on ARC or CIE batches.

**Comment by adamdecaf** [comment] 2022-09-01 21:16
Duplicate of https://github.com/moov-io/ach/issues/1072

**Closed as completed by adamdecaf** 2022-09-01 21:16 UTC
Labels: enhancement
